server:
  port: 8090
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: orkhanmustafaev93@gmail.com
    password: mwtgyixdvnytbiku
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    password: 123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  file:
    name: logs/blog.log
  level:
    az.spring.uni-tech: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
jwt:
  algorithm:
    key: SuperSecureSecretKey
  issuer: blog
  expiryInSeconds: 604800
encryption:
  salt:
    rounds: 10
email:
  from: orkhanmustafaev93@gmail.com